apiVersion: apps/v1
kind: Deployment
metadata:
  name: https-deployment
  labels:
    app: https
spec:
  replicas: 1
  selector:
    matchLabels:
      app: https
  template:
    metadata:
      labels:
        app: https
    spec:
      containers:
      - name: https-container
        image: $DEPLOY_IMAGE_NAME
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: https-configmap-file
        resources:
          requests:
            cpu: "250m"
            memory: "500Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        ports:
        - containerPort: $v2tic_port
        command: ["python", "servers/https_server.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: https-service
spec:
  type: NodePort
  selector:
    app: https
  ports:
    - protocol: TCP
      port: $v2tic_port
      targetPort: $v2tic_port
      nodePort: $v2tic_nodeport
