services:
  web:
    build:
      context: .
      target: web
    container_name: web
    ports:
      - 5173:5173
    environment:
      - VITE_ENDPOINT=http://localhost:8080
      - VITE_CNV_VOICE="<custom voice name>" # optional, used for custom voice
  backend:
    build:
      context: .
      target: backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - AZURE_OPENAI_ENDPOINT=wss://<your aoai resource>.openai.azure.com
      - AZURE_OPENAI_DEPLOYMENT=gpt-4o-realtime-preview
      - AZURE_OPENAI_KEY=<your openai key> # optional, set this for key based auth
      - SPEECH_REGION=<region>
      - SPEECH_RESOURCE_ID=<your speech resource id> # optional, set either this or SPEECH_KEY
      - SPEECH_KEY=<your speech key> # optional, set either this or SPEECH_RESOURCE_ID
      - AZURE_CLIENT_ID=<your azure client id> # optional, set this for Entra ID auth
