#  Copyright (c) Microsoft. All rights reserved.
#  See https://aka.ms/csspeech/license201809 for the full license information.

from skbuild import setup
import os
import re

# Change the PACKAGE_NAME only to change folder and different name
PACKAGE_NAME = "azure-cognitiveservices-speech"
DOTTED_PACKAGE_NAME = PACKAGE_NAME.replace('-', '.')
PACKAGE_PPRINT_NAME = "Microsoft Cognitive Services Speech SDK"
SOURCE_DIR = 'source/bindings/python/src'

DESCRIPTION = """
# Microsoft Speech SDK for Python

For an introduction to this package, have a look at [the quickstart
article](https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstart-python).

For information about the speech service, please refer to [its
website](https://docs.microsoft.com/azure/cognitive-services/speech-service/).

## Documentation

API documentation for this package can be found [here](https://aka.ms/csspeech/pythonref).
"""

version = None
try:
    version = os.environ['SPEECHSDK_SEMVER2NOMETA']
    version = re.sub(r'-alpha\.(\d+)\.', r'a\1.dev', version)
    version = re.sub(r'-beta\.(\d+)\.', r'b\1.dev', version)
    version = re.sub(r'-alpha\.(\d+)$', r'a\1', version)
    version = re.sub(r'-beta\.(\d+)$', r'b\1', version)
    version = re.sub(r'-rc\.(\d+)$', r'rc\1', version)
except KeyError:
    if os.path.isfile('version.txt'):
        with open('version.txt') as f:
            version = f.readline().strip() + 'a0.dev0'

with open(os.path.join(SOURCE_DIR, 'version.py'), 'w') as f:
    f.write('# Autogenerated during install step -- do not edit\n')
    f.write('__version__ = "{}"\n'.format(version))

if version is None:
    raise RuntimeError('Cannot find version information')

setup(name=PACKAGE_NAME,
      version=version,
      description=PACKAGE_PPRINT_NAME,
      author='Microsoft',
      url='https://docs.microsoft.com/azure/cognitive-services/speech-service/',
      package_dir={DOTTED_PACKAGE_NAME: SOURCE_DIR},
      packages=[DOTTED_PACKAGE_NAME],
      cmake_args=[
          '-DBUILD_JAVA:BOOL=OFF',
          '-DBUILD_CSHARP:BOOL=OFF',
          '-DBUILD_PYTHON:BOOL=ON',
      ],
      classifiers=[
          'Development Status :: 4 - Beta',
          'Programming Language :: Python',
          'Programming Language :: Python :: 3',
          'Programming Language :: Python :: 3.5',
          'Programming Language :: Python :: 3.6',
          'Programming Language :: Python :: 3.7',
      ],
      long_description=DESCRIPTION,
      long_description_content_type="text/markdown"
      )
