//
// Copyright (c) Microsoft. All rights reserved.
// See https://aka.ms/csspeech/license201809 for the full license information.
//

#import "SPXAudioConfiguration.h"
#import "SPXAudioDataStream.h"
#import "SPXAudioStream.h"
#import "SPXAudioStreamFormat.h"
#import "SPXAutoDetectSourceLanguageConfiguration.h"
#import "SPXAutoDetectSourceLanguageResult.h"
#import "SPXConnection.h"
#import "SPXConnectionEventArgs.h"
#import "SPXConversation.h"
#import "SPXConversationEventArgs.h"
#import "SPXConversationTranscriber.h"
#import "SPXConversationTranscriptionEventArgs.h"
#import "SPXConversationTranscriptionResult.h"
#import "SPXConversationTranslationEventArgs.h"
#import "SPXConversationTranslationResult.h"
#import "SPXConversationTranslator.h"
#import "SPXGrammar.h"
#import "SPXGrammarPhrase.h"
#import "SPXIntentRecognitionEventArgs.h"
#import "SPXIntentRecognitionResult.h"
#import "SPXIntentRecognizer.h"
#import "SPXLanguageUnderstandingModel.h"
#import "SPXKeywordRecognitionEventArgs.h"
#import "SPXKeywordRecognitionResult.h"
#import "SPXKeywordRecognizer.h"
#import "SPXKeywordRecognitionModel.h"
#import "SPXParticipant.h"
#import "SPXPhraseListGrammar.h"
#import "SPXPronunciationAssessmentConfiguration.h"
#import "SPXPronunciationAssessmentResult.h"
#import "SPXPropertyCollection.h"
#import "SPXRecognitionEventArgs.h"
#import "SPXRecognitionResult.h"
#import "SPXRecognizer.h"
#import "SPXSessionEventArgs.h"
#import "SPXSpeechConfiguration.h"
#import "SPXSpeechRecognitionEventArgs.h"
#import "SPXSpeechRecognitionResult.h"
#import "SPXSpeechRecognizer.h"
#import "SPXSpeechSynthesisCancellationDetails.h"
#import "SPXSpeechSynthesisEventArgs.h"
#import "SPXSpeechSynthesizer.h"
#import "SPXSpeechTranslationConfiguration.h"
#import "SPXSourceLanguageConfiguration.h"
#import "SPXTranslationRecognitionEventArgs.h"
#import "SPXTranslationRecognitionResult.h"
#import "SPXTranslationRecognizer.h"
#import "SPXTranslationSynthesisEventArgs.h"
#import "SPXTranslationSynthesisResult.h"
#import "SPXUser.h"
