#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license.
#

parameters:
  dependsOn: ''
  condition: succeeded()

jobs:

- job: JsBuild
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  pool:
    name: Hosted VS2017
    demands: npm
  timeoutInMinutes: 60
  steps:
  - bash: npm ci && npm run civersion
    displayName: Set version
    workingDirectory: $(SPEECHSDK_JS_ROOT)
  - bash: |
      F=$(SPEECHSDK_JS_ROOT)/src/common.speech/RecognizerConfig.ts
      [[ -f $F ]] || exit 1
      perl -i.bak -p -e 'BEGIN { $c = 0 } $c += s/(?<=const SPEECHSDK_CLIENTSDK_VERSION = ")[^"]*/$(SPEECHSDK_SEMVER2NOMETA)/g; END { die "Patched SPEECHSDK_CLIENTSDK_VERSION $c time(s), expected 1.\n" if $c != 1 }' "$F"
      E=$?
      rm -f "$F.bak"
      git diff
      exit $E
    displayName: Stamp SPEECHSDK_CLIENTSDK_VERSION
  - bash: npm run build && npm pack
    displayName: Build and pack SDK
    workingDirectory: $(SPEECHSDK_JS_ROOT)
  - script: |
      RunTests.cmd ^
        SpeechSubscriptionKey:$(speech-ne-s0-key1) ^
        SpeechRegion:northeurope ^
        LuisSubscriptionKey:$(luis-westus-s0-201809-key1) ^
        LuisRegion:westus ^
        SpeechTestEndpointId:ec3432b2-8584-4736-865a-556213b9f6fd
    displayName: Run tests
    workingDirectory: $(SPEECHSDK_JS_ROOT)
  - task: PublishTestResults@2
    displayName: Publish test results
  - bash: |
      set -u -e -o pipefail -x
      PACKAGE_BASE=microsoft-cognitiveservices-speech-sdk
      PACKAGE_NAME=$PACKAGE_BASE-$SPEECHSDK_SEMVER2NOMETA.tgz
      PACKAGE_IN=$(SPEECHSDK_JS_ROOT)/$PACKAGE_NAME
      PACKAGE_OUT="$(Build.ArtifactStagingDirectory)/Out/JavaScript/npm"
      ZIP_OUT="$(Build.ArtifactStagingDirectory)/Out/JavaScript/SpeechSDK-JavaScript-$SPEECHSDK_SEMVER2NOMETA"
      mkdir -p "$PACKAGE_OUT" "$ZIP_OUT"
      cp --preserve "$PACKAGE_IN" "$PACKAGE_OUT"
      echo SRI hash for microsoft.cognitiveservices.speech.sdk.bundle.js: sha512-"$(openssl dgst -sha512 -binary $(SPEECHSDK_JS_ROOT)/distrib/browser/microsoft.cognitiveservices.speech.sdk.bundle.js | openssl base64 -A)"
      cp --preserve $(SPEECHSDK_JS_ROOT)/LICENSE $(SPEECHSDK_JS_ROOT)/REDIST.txt $(SPEECHSDK_JS_ROOT)/distrib/browser/microsoft.cognitiveservices.speech.sdk.bundle.* "$ZIP_OUT"
    displayName: Create drop
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: $(Build.ArtifactStagingDirectory)/Out/JavaScript/SpeechSDK-JavaScript-$(SPEECHSDK_SEMVER2NOMETA)
      includeRootFolder: true
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/Out/JavaScript/SpeechSDK-JavaScript-$(SPEECHSDK_SEMVER2NOMETA).zip
    displayName: Create .zip
  - bash: rm -rf "$(Build.ArtifactStagingDirectory)/Out/JavaScript/SpeechSDK-JavaScript-$(SPEECHSDK_SEMVER2NOMETA)"
    displayName: Remove temporary directory
  - task: PublishBuildArtifacts@1
    displayName: Publish drop
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Out/JavaScript'
      ArtifactName: JavaScript
      publishLocation: Container
