target 'SpeechSDKSwift' do
  platform :ios, '9.3'
  pod 'MicrosoftCognitiveServicesSpeech-iOS', :path => "{{{PODSPEC_PATH}}}"
  use_frameworks!
end
target 'SpeechSDKSwiftTests' do
  platform :ios, '9.3'
  pod 'MicrosoftCognitiveServicesSpeech-iOS', :path => "{{{PODSPEC_PATH}}}"
  use_frameworks!
end
