from typing import Final

UTF_8: Final[str] = 'utf_8'
US_ASCII: Final[str] = 'us-ascii'
BASE64: Final[str] = 'base64'
UNCONVERTIBLE: Final[str] = 'Unconvertible'
TRANSCRIBED: Final[str] = 'Transcribed'
TRUE: Final[str] = 'true'
FALSE: Final[str] = 'false'
SUCCESS: Final[str] = 'Success'
FAILED: Final[str] = 'Failed'
PENDING: Final[str] = 'Pending'
BLANK_MESSAGE: Final[str] = ''
EJECTOR: Final[str] = 'ejector'
V2TIC: Final[str] = 'v2tic'
SKIPPING: Final[str] = 'skipping'
CONTEXT: Final[str] = 'context'
ACS_CLIENT: Final[str] = 'acs_client'