target 'SpeechSDKOsxSwift' do
  platform :osx, 10.14
  pod 'MicrosoftCognitiveServicesSpeech-macOS', :path => "{{{PODSPEC_PATH}}}"
  use_frameworks!
end
target 'SpeechSDKOsxSwiftTests' do
  platform :osx, 10.14
  pod 'MicrosoftCognitiveServicesSpeech-macOS', :path => "{{{PODSPEC_PATH}}}"
  use_frameworks!
end
