# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'CocoaPodsSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'Microsoft-CognitiveServices-Speech-for-iOS', :podspec => '../../../../../source/bindings/objective-c/cocoapods/Microsoft-CognitiveServices-Speech-for-iOS.podspec'

  # Pods for CocoaPodsSample

  target 'CocoaPodsSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
