# Uncomment the next line to define a global platform for your project
platform :osx, '10.13'

target 'SpeechSDK' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'Microsoft-CognitiveServices-Speech-for-OSX', :podspec => '../../../../source/bindings/objective-c/cocoapods/Microsoft-CognitiveServices-Speech-for-OSX.podspec'

  # Pods for SpeechSDK

  target 'SpeechSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
