/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_cognitiveservices_speech_transcription_ConversationTranscriber */

#ifndef _Included_com_microsoft_cognitiveservices_speech_transcription_ConversationTranscriber
#define _Included_com_microsoft_cognitiveservices_speech_transcription_ConversationTranscriber
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_cognitiveservices_speech_transcription_ConversationTranscriber
 * Method:    createConversationTranscriberFromConfig
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_transcription_ConversationTranscriber_createConversationTranscriberFromConfig
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_microsoft_cognitiveservices_speech_transcription_ConversationTranscriber
 * Method:    joinConversation
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_transcription_ConversationTranscriber_joinConversation
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_microsoft_cognitiveservices_speech_transcription_ConversationTranscriber
 * Method:    leaveConversation
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_transcription_ConversationTranscriber_leaveConversation
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
