/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_cognitiveservices_speech_translation_TranslationSynthesisEventArgs */

#ifndef _Included_com_microsoft_cognitiveservices_speech_translation_TranslationSynthesisEventArgs
#define _Included_com_microsoft_cognitiveservices_speech_translation_TranslationSynthesisEventArgs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_cognitiveservices_speech_translation_TranslationSynthesisEventArgs
 * Method:    getSynthesisResult
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;Lcom/microsoft/cognitiveservices/speech/util/IntRef;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_translation_TranslationSynthesisEventArgs_getSynthesisResult
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
