/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_cognitiveservices_speech_transcription_ConversationTranscriptionResult */

#ifndef _Included_com_microsoft_cognitiveservices_speech_transcription_ConversationTranscriptionResult
#define _Included_com_microsoft_cognitiveservices_speech_transcription_ConversationTranscriptionResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_cognitiveservices_speech_transcription_ConversationTranscriptionResult
 * Method:    getUserId
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;Lcom/microsoft/cognitiveservices/speech/util/StringRef;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_transcription_ConversationTranscriptionResult_getUserId
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
