/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_cognitiveservices_speech_ClassLanguageModel */

#ifndef _Included_com_microsoft_cognitiveservices_speech_ClassLanguageModel
#define _Included_com_microsoft_cognitiveservices_speech_ClassLanguageModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_cognitiveservices_speech_ClassLanguageModel
 * Method:    fromStorageId
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/IntRef;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_ClassLanguageModel_fromStorageId
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_microsoft_cognitiveservices_speech_ClassLanguageModel
 * Method:    assignClass
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;Ljava/lang/String;Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_ClassLanguageModel_assignClass
  (JNIEnv *, jobject, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
