/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_cognitiveservices_speech_util_SafeHandle */

#ifndef _Included_com_microsoft_cognitiveservices_speech_util_SafeHandle
#define _Included_com_microsoft_cognitiveservices_speech_util_SafeHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseEventHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseEventHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseRecognizerHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseRecognizerHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseConversationTranslatorHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseConversationTranslatorHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseSpeechConfigHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseSpeechConfigHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseAudioConfigHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseAudioConfigHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releasePropertyHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releasePropertyHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseRecognizerResultHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseRecognizerResultHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseConnectionHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseConnectionHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseAudioInputStreamHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseAudioInputStreamHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseAudioOutputStreamHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseAudioOutputStreamHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseAudioStreamFormatHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseAudioStreamFormatHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseKeywordModelHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseKeywordModelHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseLanguageUnderstandingModelHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseLanguageUnderstandingModelHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseIntentTriggerHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseIntentTriggerHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseUserHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseUserHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseParticipantHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseParticipantHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseConversationHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseConversationHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseDialogServiceConnectorHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseDialogServiceConnectorHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseDialogServiceConnectorEventHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseDialogServiceConnectorEventHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseAutoDetectSourceLanguageConfigHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseAutoDetectSourceLanguageConfigHandle
(JNIEnv*, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseSourceLanguageConfigHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseSourceLanguageConfigHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseSynthesisEventHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseSynthesisEventHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseSynthesisResultHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseSynthesisResultHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseAudioDataStreamHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseAudioDataStreamHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseSynthesizerHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseSynthesizerHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseGrammarHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseGrammarHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseTranslationSynthesisHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseTranslationSynthesisHandle
(JNIEnv*, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_util_SafeHandle
 * Method:    releaseKeywordRecognizerHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_util_SafeHandle_releaseKeywordRecognizerHandle
(JNIEnv*, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
