/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_cognitiveservices_speech_intent_IntentTrigger */

#ifndef _Included_com_microsoft_cognitiveservices_speech_intent_IntentTrigger
#define _Included_com_microsoft_cognitiveservices_speech_intent_IntentTrigger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_cognitiveservices_speech_intent_IntentTrigger
 * Method:    createFromPhrase
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/IntRef;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_intent_IntentTrigger_createFromPhrase
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_microsoft_cognitiveservices_speech_intent_IntentTrigger
 * Method:    createFromLanguageUnderstandingModel
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/IntRef;Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_intent_IntentTrigger_createFromLanguageUnderstandingModel
  (JNIEnv *, jclass, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
