/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_cognitiveservices_speech_dialog_CustomCommandsConfig */

#ifndef _Included_com_microsoft_cognitiveservices_speech_dialog_CustomCommandsConfig
#define _Included_com_microsoft_cognitiveservices_speech_dialog_CustomCommandsConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_CustomCommandsConfig
 * Method:    fromSubscription
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/IntRef;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_CustomCommandsConfig_fromSubscription
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring);

/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_CustomCommandsConfig
 * Method:    fromAuthorizationToken
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/IntRef;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_CustomCommandsConfig_fromAuthorizationToken
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
