/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector */

#ifndef _Included_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
#define _Included_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
 * Method:    createDialogServiceConnectorFomConfig
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_createDialogServiceConnectorFomConfig
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
 * Method:    connect
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_connect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
 * Method:    disconnect
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_disconnect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
 * Method:    sendActivity
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;Lcom/microsoft/cognitiveservices/speech/util/StringRef;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_sendActivity
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
 * Method:    listenOnce
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;Lcom/microsoft/cognitiveservices/speech/util/IntRef;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_listenOnce
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
 * Method:    startKeywordRecognition
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_startKeywordRecognition
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
 * Method:    stopKeywordRecognition
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_stopKeywordRecognition
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
 * Method:    recognizingSetCallback
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_recognizingSetCallback
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
 * Method:    recognizedSetCallback
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_recognizedSetCallback
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
 * Method:    sessionStartedSetCallback
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_sessionStartedSetCallback
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
 * Method:    sessionStoppedSetCallback
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_sessionStoppedSetCallback
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
 * Method:    canceledSetCallback
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_canceledSetCallback
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
 * Method:    activityReceivedSetCallback
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_activityReceivedSetCallback
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector
 * Method:    getPropertyBagFromDialogServiceConnectorHandle
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;Lcom/microsoft/cognitiveservices/speech/util/IntRef;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_getPropertyBagFromDialogServiceConnectorHandle
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
