/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_cognitiveservices_speech_audio_AudioStreamFormat */

#ifndef _Included_com_microsoft_cognitiveservices_speech_audio_AudioStreamFormat
#define _Included_com_microsoft_cognitiveservices_speech_audio_AudioStreamFormat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_cognitiveservices_speech_audio_AudioStreamFormat
 * Method:    createFromDefaultInput
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_audio_AudioStreamFormat_createFromDefaultInput
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_microsoft_cognitiveservices_speech_audio_AudioStreamFormat
 * Method:    createFromWaveFormatPCM
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;JSS)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_audio_AudioStreamFormat_createFromWaveFormatPCM
  (JNIEnv *, jclass, jobject, jlong, jshort, jshort);

/*
 * Class:     com_microsoft_cognitiveservices_speech_audio_AudioStreamFormat
 * Method:    createFromCompressedFormat
 * Signature: (Lcom/microsoft/cognitiveservices/speech/util/SafeHandle;I)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_cognitiveservices_speech_audio_AudioStreamFormat_createFromCompressedFormat
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
