name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Clean Solution
      run: dotnet clean ./samples/ingestion/ingestion-client/BatchIngestionClient.sln --configuration Release && dotnet nuget locals all --clear
    - name: Build BatchIngestionClient
      run: dotnet build BatchIngestionClient --configuration Release
    - name: Publish StartTranscriptionByTimer function
      run: dotnet publish -c Release -f netcoreapp3.1 --no-self-contained --output ./StartTranscriptionByTimer samples/ingestion/ingestion-client/StartTranscriptionByTimer/StartTranscriptionByTimer.csproj
    - name: Publish StartTranscriptionByServiceBus function
      run: dotnet publish -c Release -f netcoreapp3.1 --no-self-contained --output ./StartTranscriptionByServiceBus samples/ingestion/ingestion-client/StartTranscriptionByServiceBus/StartTranscriptionByServiceBus.csproj
    - name: Publish FetchTranscription function
      run: dotnet publish -c Release -f netcoreapp3.1 --no-self-contained --output ./FetchTranscription samples/ingestion/ingestion-client/FetchTranscription/FetchTranscription.csproj
    - name: Publish \RealtimeTranscription function
      run: dotnet publish -c Release -f netcoreapp3.1 --no-self-contained --output ./RealtimeTranscription samples/ingestion/ingestion-client/RealtimeTranscription/RealtimeTranscription.csproj
    - name: Upload StartTranscriptionByTimer function
      uses: actions/upload-artifact@v1
      with:
        name: StartTranscriptionByTimer
        path: ./StartTranscriptionByTimer
    - name: Upload StartTranscriptionByServiceBus function
      uses: actions/upload-artifact@v1
      with:
        name: StartTranscriptionByServiceBus
        path: ./StartTranscriptionByServiceBus
    - name: Upload FetchTranscription function
      uses: actions/upload-artifact@v1
      with:
        name: FetchTranscription
        path: ./FetchTranscription
